{
 "title": "OPA Violations",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OPA Violations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "opa_scorecard_violations{violating_namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "OPA Violations Over Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(opa_scorecard_violations{violating_namespace=\"$namespace\"})",
     "legendFormat": "Overall OPA violations per namespace"
    }
   ]
  },
  {
   "title": "Total Violations by kind",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kind) (opa_scorecard_violations{violating_namespace=\"$namespace\"})",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "Enforcement Actions",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(opa_scorecard_constraint_information{enforcementAction=\"dryrun\"})",
     "legendFormat": "enforcementAction=\"dryrun\""
    },
    {
     "expr": "sum(opa_scorecard_constraint_information{enforcementAction=\"deny\"})",
     "legendFormat": "enforcementAction=\"deny\""
    },
    {
     "expr": "sum(opa_scorecard_constraint_information{enforcementAction=\"warn\"})"
    }
   ]
  }
 ]
}