apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: opa-exporter
  namespace: opa-exporter
spec:
  endpoints:
    - interval: 15s
      port: 9141-9141
      scheme: http
  namespaceSelector:
    matchNames:
      - opa-exporter
  selector:
    matchLabels:
      app: opa-exporter